server {
  listen 80;

  # Folder where your React app build files are copied
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # This line is the key — it tells Nginx to serve index.html for React routes
    try_files $uri /index.html;
  }

  error_page 500 502 503 504 /index.html;
}
